name: Dependency Updates

on:
  schedule:
    - cron: "0 5 * * 3"

jobs:
  dependabot:
    name: Check dependency updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: Check outdated
        run: npm outdated || true
